### ISSUE TITLE
The score for representative genes in the genetree docs can be negative

### ISSUE THREAD

**Issue by mycrobe** [warelab/gramene-swagger#10]
Test failures on gramene-search-client caused by negative scores for representative genes in a genetree document, e.g. note `"score": -150` in the following snippet

``` js
{
        "_id": "EPlGT00140000001539",
        // skip many properties, children and levels of indentation
        "children": [
            {
                "node_id": 633840,
                "gene_stable_id": "fgenesh2_kg.6__1471__AT5G14930.2",
                // skip other properties
                "representative": {
                    "id": "fgenesh2_kg.6__1471__AT5G14930.2",
                    "score": -150
                }
            }
        ]
    }
```

contradicts with [the following in `swagger.yaml`](https://github.com/warelab/gramene-swagger/blob/dev/api/swagger/swagger.yaml#L992)

``` yaml
  GenetreeLeafNode:
    properties:
      # other properties skipped…
      representative:
        required:
          - id
          - score
        properties:
          id:
            type: string
          score:
            type: number
            # ** NOTE FOLLOWING LINE SHOULD BE REMOVED **
            minimum: 0.0
```

The last line in the yaml snippet should be removed.
